#!/usr/bin/env bash
# Reproducibly captures Paider's real terminal output for design/TUI-REVIEW.md.
#
# Every file under design/captures/ is generated by this script — do not hand-edit
# a .ans file. Re-run `design/capture.sh` any time app/ output changes and re-run
# the review against the fresh captures.
#
# Colored captures allocate a real pty via `script` and resize it with `stty cols`
# (setting the COLUMNS env var alone does NOT change what an app reading terminal
# ioctl sees). `script` on macOS prints a leading EOT+backspace+backspace+CR
# artifact before real output starts; strip_pty_artifact() removes exactly that.
#
# -nocolor captures set NO_COLOR=1 with no --ansi flag (tests whether the app
# actually honors NO_COLOR, not whether --ansi can override it).
# -piped captures redirect straight to a file with no pty and no --ansi flag
# (tests real non-TTY auto-detection, matching how a user's shell pipe behaves).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$REPO_ROOT/design/captures"
PAIDER="$REPO_ROOT/paider"

mkdir -p "$OUT_DIR"

# Strips the leading `^D^H^H` (+ optional CR LF) artifact that macOS `script` +
# `stty` emits before the child process's real first byte. It is the *literal
# two-character* echo of a control-D keypress (caret, D — echoctl style, bytes
# 5e 44), followed by two backspaces that erase it, and — when the real output
# doesn't start with its own escape sequence — a CR LF. Not a raw 0x04 EOT byte.
strip_pty_artifact() {
    local file="$1"
    perl -0777 -pe 's/\A\^D\x08\x08\r?\n?//' -i "$file"
}

# capture_pty <outfile> <cols> <workdir> <no_color:0|1> -- <command...>
capture_pty() {
    local outfile="$1" cols="$2" workdir="$3" nocolor="$4"
    shift 4
    [[ "$1" == "--" ]] && shift
    local cmd="$*"
    if [[ "$nocolor" == "1" ]]; then
        NO_COLOR=1 script -q /dev/null sh -c "cd '$workdir' && stty cols $cols && $cmd" > "$outfile" 2>&1 || true
    else
        script -q /dev/null sh -c "cd '$workdir' && stty cols $cols && $cmd" > "$outfile" 2>&1 || true
    fi
    strip_pty_artifact "$outfile"
}

# capture_piped <outfile> <workdir> -- <command...>
capture_piped() {
    local outfile="$1" workdir="$2"
    shift 2
    [[ "$1" == "--" ]] && shift
    local cmd="$*"
    (cd "$workdir" && eval "$cmd") > "$outfile" 2>&1 || true
}

seed_cost_db() {
    local workdir="$1"
    mkdir -p "$workdir/.paider"
    php -r '
        $d = new PDO("sqlite:" . $argv[1] . "/.paider/paider.db");
        $d->exec("CREATE TABLE IF NOT EXISTS events (id TEXT PRIMARY KEY, type TEXT NOT NULL, payload TEXT NOT NULL, created_at TEXT NOT NULL)");
        $d->prepare("INSERT INTO events VALUES (?,?,?,?)")->execute([
            "e1", "tier_call",
            json_encode(["tier" => "orchestrator", "model" => "anthropic/claude-opus-5", "tokens_in" => 61200, "tokens_out" => 19800, "cost_usd" => 0.801]),
            gmdate("c"),
        ]);
    ' "$workdir"
}

echo "== plain workdir (no db, no settings) =="
PLAIN_DIR="$(mktemp -d)"

echo "== seeded-cost workdir =="
COST_DIR="$(mktemp -d)"
seed_cost_db "$COST_DIR"

echo "== provider workdir (isolated so config:provider mutation never touches the repo) =="
PROVIDER_DIR="$(mktemp -d)"

for width in 80 120; do
    capture_pty "$OUT_DIR/help-${width}col.ans"            "$width" "$PLAIN_DIR"    0 -- "'$PAIDER' --help"
    capture_pty "$OUT_DIR/list-${width}col.ans"             "$width" "$PLAIN_DIR"    0 -- "'$PAIDER' list"
    capture_pty "$OUT_DIR/config-show-${width}col.ans"      "$width" "$PLAIN_DIR"    0 -- "'$PAIDER' config:show"
    capture_pty "$OUT_DIR/config-provider-${width}col.ans"  "$width" "$PROVIDER_DIR" 0 -- "'$PAIDER' config:provider open"
    capture_pty "$OUT_DIR/bad-cmd-${width}col.ans"          "$width" "$PLAIN_DIR"    0 -- "'$PAIDER' notarealcommand"
    capture_pty "$OUT_DIR/cost-nodb-${width}col.ans"        "$width" "$PLAIN_DIR"    0 -- "'$PAIDER' cost"
    capture_pty "$OUT_DIR/cost-${width}col.ans"             "$width" "$COST_DIR"     0 -- "'$PAIDER' cost"
done

# Accessibility variants — always at 80 columns, always exactly one axis changed.
capture_pty   "$OUT_DIR/list-80col-nocolor.ans" 80 "$PLAIN_DIR" 1 -- "'$PAIDER' list"
capture_pty   "$OUT_DIR/cost-80col-nocolor.ans" 80 "$COST_DIR"  1 -- "'$PAIDER' cost"
capture_piped "$OUT_DIR/list-80col-piped.ans"      "$PLAIN_DIR"    -- "'$PAIDER' list"
capture_piped "$OUT_DIR/cost-80col-piped.ans"      "$COST_DIR"     -- "'$PAIDER' cost"

rm -rf "$PLAIN_DIR" "$COST_DIR" "$PROVIDER_DIR"

echo "== width-invariance check =="
for base in help list config-show cost bad-cmd cost-nodb; do
    a="$OUT_DIR/${base}-80col.ans"
    b="$OUT_DIR/${base}-120col.ans"
    if cmp -s "$a" "$b"; then
        echo "  $base: byte-identical at 80 and 120 cols"
    else
        echo "  $base: DIFFERS between 80 and 120 cols"
    fi
done

echo "== NO_COLOR probe (informational; see finding 1) =="
esc_with="$(grep -c $'\x1b' "$OUT_DIR/list-80col.ans" || true)"
esc_without="$(grep -c $'\x1b' "$OUT_DIR/list-80col-nocolor.ans" || true)"
echo "  list-80col.ans: $esc_with ESC-bearing lines"
echo "  list-80col-nocolor.ans: $esc_without ESC-bearing lines"

echo "Done. Captures written to $OUT_DIR"
